export default {
  vi: {
    code: {
      "000": "Đã có lỗi sảy ra",
      "001": "Tài khoản đã tồn tại",
      "002": "Đăng ký tài khoản thành công",
      "003": "Đăng nhập thành công",
      "004": "Mật khẩu sai",
      "005": "Tài khoản không tồn tại",
      "006": "Tên đăng nhập hoặc mật khẩu ít hơn 6 ký tự",
    },
    login: {
      title: "Đăng nhập tài khoản Zalo để kết nối với ứng dụng Zalo Web",
      password: "Mật khẩu",
      username: "Tên đăng nhập",
      loginwithpassword: "Đăng nhập với mật khẩu",
      forgotpassword: "Quên mật khẩu?",
      noaccount: "Bạn chưa có tài khoản ?",
      registernewaccount: "Đăng ký tài khoản mới",
    },
    register: {
      title: "Đăng ký tài khoản Zalo để kết nối với ứng dụng Zalo Web",
      password: "Mật khẩu",
      username: "Tên đăng nhập",
      showname: "Tên hiển thị",
      register: "Đăng ký",
      backlogin: "Quay về trang log in",
      male: "Nam",
      female: "Nữ",
    },
    mainlayout: {
      message: "Tin nhắn",
      phonebook: "Danh bạ",
      todo: "To-Do",
      mycloude: "Cloude của tôi",
      setting: "Cài đặt",
      screencapture: "Chụp màn hình không kèm cửa sổ",
      tool: "Công cụ",
      zavi: "Zavi",
      setting: "Cài đặt",
      search: "Tìm kiếm",
      addfriend: "Thêm bạn",
      creategroupchat: "Tạo nhóm chat",
      close: "Đóng",
    },
    nopage: {
      backhome: "Quay về trang chủ",
    },
    navlist: {
      listfriend: "Danh sách bạn bè",
      listgroup: "Danh sách nhóm",
      requestfriend: "Lời mời kết bạn",
      waitingagree: "Đã gửi lời mời",
    },
    detailcontent: {
      waitingagree: "Đã gửi lời mời",
      searchmessage: "Tìm kiếm tin nhắn",
      infoconversation: "Thông tin hội thoại",
      agree: "Đồng ý",
      addfriend: "Kết bạn",
      isfriend: "Đã là bạn",
      findinmessage: "Tìm kiếm trong tin nhắn",
      inputmesageto: "Nhập tin nhắn tới ",
      send: "GỬI",
      you: "Bạn",
      sendimage: "Gửi hình ảnh",
      image: "Hình ảnh",
      seeall: "Xem tất cả",
      link: "Link",
    },
    module: {
      cantfinduser: "Không tìm thấy người dùng",
      confirm: "Xác nhận",
      no: "Không",
      remove: "Xóa",
      outlistfriend: "khỏi danh sách bạn bè ?",
      plsenterusername: "Hãy nhập username cần kết bạn !",
      youwantlogout: "Bạn có muốn đăng xuất khỏi Zalo?",
      logout: "Đăng xuất",
      infoaccount: "Thông tin tài khoản",
      infopersonal: "Thông tin cá nhân",
      updateinfo: "Cập nhật thông tin",
      showname: "Tên hiển thị",
      pleaseuserealname: "Sử dụng tên thật để bạn bè dễ dàng nhận diện hơn",
      update: "Cập nhật",
      cancel: "Hủy",
      addfriend: "Thêm bạn",
      username: "Tên đăng nhập (username)",
      image: "Hình ảnh",
      link: "Liên kết",
      sex: "Giới tính",
      male: "Nam",
      female: "Nữ",
      unupdate: "Chưa cập nhật",
    },
    popper: {
      watchinfo: "Xem thông tin",
      namechangereminder: "Đổi tên gợi nhớ",
      removefriend: "Xóa bạn",
      infoofyou: "Hồ sơ của bạn",
      infoaccount: "Thông tin tài khoản",
      setting: "Cài đặt",
      logout: "Đăng xuất",
      language: "Ngôn ngữ",
    },
    welcome: {
      title: "Chào mừng đến với ",
      description:
        "Khám phá những tiện ích hỡ trợ làm việc và trò truyện cùng người thân, bạn bè được tối ưu hóa cho máy tính của bạn.",
      slide0: {
        title: "Gọi nhóm và làm việc hiệu quả với Zalo Group Call",
        description: "Trao đổi công việc mọi lúc, mọi nơi",
      },
      slide1: {
        title: "Giải quyết công việc hiệu quả hơn, lên đến 40%",
        description: "Với Zalo Web",
      },
      slide2: {
        title: "Chat nhóm với đồng nghiệp",
        description: "Tiện lợi hơn, nhờ công cụ chat trên máy tính",
      },
      slide3: {
        title: "Gửi file nặng?",
        description: "Đã có Zalo Web xửa hết",
      },
      slide4: {
        title: "Trải nghiệm xuyên suốt",
        description:
          "Kết nối và giải quyết công việc trên mọi thiết bị với dữ liệu luôn được đồng bộ",
      },
      slide5: {
        title: "Xuất dữ liệu khi chuyển máy, đổi máy tính mới",
        description:
          "Bây giờ bạn có thể dễ dàng xuất dữ liệu và nhập dữ liệu lịch sử trò truyện của mình khi thay đổi máy tính mới",
      },
      slide6: {
        title: "Tin nhắn tự xóa",
        description:
          "Tự giờ tin nhắn có thể tự xóa sau khoảng thời gian nhất định",
      },
      slide7: {
        title: "Mã hóa đầu cuối",
        description:
          "Nội dung tin nhắn được mã hóa trong suốt quá trình xóa và nhận",
      },
      slide8: {
        title: "Nhắn tin nhiều hơn, soạn thảo ít hơn",
        description:
          "Sử dụng tin nhắn nhanh để lưa trữ các tin nhắn thường dùng và gửi nhanh trong hội thoại bất kỳ",
      },
    },
  },
  en: {
    code: {
      "000": "An error has occurred",
      "001": "Account already exists",
      "002": "Account already exists",
      "003": "Logged in successfully",
      "004": "Wrong password",
      "005": "Account does not exist",
      "006": "Username or password less than 6 characters",
    },
    login: {
      title:
        "Log in to your Zalo account to connect to the Zalo Web application",
      password: "Password",
      username: "Username",
      loginwithpassword: "Login with password",
      forgotpassword: "Forgot password?",
      noaccount: "Do not have an account ?",
      registernewaccount: "Register a new account",
    },
    register: {
      title:
        "Register for a Zalo account to connect to the Zalo Web application",
      password: "Password",
      username: "Username",
      showname: "Display name",
      register: "Register",
      backlogin: "Back to login page",
      male: "Male",
      female: "Female",
    },
    mainlayout: {
      message: "Message",
      phonebook: "Phonebook",
      todo: "To-Do",
      mycloude: "My Cloud",
      setting: "Setting",
      screencapture: "Screenshot without window",
      tool: "Tool",
      zavi: "Zavi",
      search: "Search",
      addfriend: "Add friend",
      creategroupchat: "Create group chat",
      close: "Close",
    },
    nopage: {
      backhome: "Back to home page",
    },
    navlist: {
      listfriend: "Friends List",
      listgroup: "Group list",
      requestfriend: "Friend request",
      waitingagree: "Invitation sent",
    },
    detailcontent: {
      waitingagree: "Invitation sent",
      searchmessage: "Message search",
      infoconversation: "Conversation information",
      agree: "Agree",
      addfriend: "Add friend",
      isfriend: "Already a friend",
      findinmessage: "Search in messages",
      inputmesageto: "Enter a message to ",
      send: "SEND",
      you: "You",
      sendimage: "Send image",
      image: "Image",
      seeall: "See all",
      link: "Link",
    },
    module: {
      cantfinduser: "User not found",
      confirm: "Confirm",
      no: "No",
      remove: "Remove",
      outlistfriend: "from your friends list?",
      plsenterusername:
        "Please enter the username you want to make friends with!",
      youwantlogout: "Do you want to sign out of Zalo?",
      logout: "Log out",
      infoaccount: "Account information",
      infopersonal: "Personal information",
      updateinfo: "Update information",
      showname: "Display name",
      pleaseuserealname:
        "Use your real name to make it easier for your friends to recognize you",
      update: "Update",
      cancel: "Cancel",
      addfriend: "Add friend",
      username: "Username",
      image: "Image",
      link: "Linh",
      sex: "Sex",
      male: "Male",
      female: "Female",
      unupdate: "Not update",
    },
    popper: {
      watchinfo: "Watch information",
      namechangereminder: "Rename reminder",
      removefriend: "Remove friend",
      infoofyou: "Your profile",
      infoaccount: "Account information",
      setting: "Setting",
      logout: "Log out",
      language: "Language",
    },
    welcome: {
      title: "Welcome to ",
      description:
        "Discover utilities to help you work and chat with family and friends optimized for your computer.",
      slide0: {
        title: "Call groups and work effectively with Zalo Group Call",
        description: "Exchange work anytime, anywhere",
      },
      slide1: {
        title: "Deal with work more efficiently, up to 40%",
        description: "With Zalo Web",
      },
      slide2: {
        title: "Group chat with colleagues",
        description: "More convenient, thanks to the chat tool on the computer",
      },
      slide3: {
        title: "Sending heavy files?",
        description: "There is already Zalo Web to fix it all",
      },
      slide4: {
        title: "Through experience",
        description: "Connect and work on any device with data always in sync",
      },
      slide5: {
        title: "Export data when transferring machines, changing new computers",
        description:
          "Now you can easily export and import your chat history data when you change to a new computer",
      },
      slide6: {
        title: "Self-deleting messages",
        description:
          "Messages can automatically delete themselves after a certain amount of time",
      },
      slide7: {
        title: "End-to-end encryption",
        description: "Message content is encrypted during deletion and receipt",
      },
      slide8: {
        title: "Text more, compose less",
        description:
          "Use instant messaging to store frequently used messages and send them quickly in any conversation",
      },
    },
  },
};
