export default {
  vi: {
    code: {
      "000": "Đã có lỗi sảy ra",
      "001": "Tài khoản đã tồn tại",
      "002": "Đăng ký tài khoản thành công",
      "003": "Đăng nhập thành công",
      "004": "Mật khẩu sai",
      "005": "Tài khoản không tồn tại",
      "006": "Tên đăng nhập hoặc mật khẩu ít hơn 6 ký tự",
    },
    login: {
      title: "Đăng nhập tài khoản Zalo để kết nối với ứng dụng Zalo Web",
      password: "Mật khẩu",
      username: "Tên đăng nhập",
      loginwithpassword: "Đăng nhập với mật khẩu",
      forgotpassword: "Quên mật khẩu?",
      noaccount: "Bạn chưa có tài khoản ?",
      registernewaccount: "Đăng ký tài khoản mới",
    },
    register: {
      title: "Đăng ký tài khoản Zalo để kết nối với ứng dụng Zalo Web",
      password: "Mật khẩu",
      username: "Tên đăng nhập",
      showname: "Tên hiển thị",
      register: "Đăng ký",
      backlogin: "Quay về trang log in",
      male: "Nam",
      female: "Nữ",
    },
    mainlayout: {
      message: "Tin nhắn",
      phonebook: "Danh bạ",
      todo: "To-Do",
      mycloude: "Cloude của tôi",
      setting: "Cài đặt",
      screencapture: "Chụp màn hình không kèm cửa sổ",
      tool: "Công cụ",
      zavi: "Zavi",
      setting: "Cài đặt",
      search: "Tìm kiếm",
      addfriend: "Thêm bạn",
      creategroupchat: "Tạo nhóm chat",
      close: "Đóng",
    },
    nopage: {
      backhome: "Quay về trang chủ",
    },
    navlist: {
      listfriend: "Danh sách bạn bè",
      listgroup: "Danh sách nhóm",
      requestfriend: "Lời mời kết bạn",
      waitingagree: "Đã gửi lời mời",
    },
    detailcontent: {
      waitingagree: "Đã gửi lời mời",
      searchmessage: "Tìm kiếm tin nhắn",
      infoconversation: "Thông tin hội thoại",
      agree: "Đồng ý",
      addfriend: "Kết bạn",
      isfriend: "Đã là bạn",
      findinmessage: "Tìm kiếm trong tin nhắn",
      infoconversation: "Thông tin hội thoại",
      inputmesageto: "Nhập tin nhắn tới ",
      send: "GỬI",
      you: "Bạn",
    },
    module: {
      cantfinduser: "Không tìm thấy người dùng",
      confirm: "Xác nhận",
      no: "Không",
      remove: "Xóa",
      outlistfriend: "khỏi danh sách bạn bè ?",
      plsenterusername: "Hãy nhập username cần kết bạn !",
    },
    popper: {
      watchinfo: "Xem thông tin",
      namechangereminder: "Đổi tên gợi nhớ",
      removefriend: "Xóa bạn",
    },
  },
};
