export default {
  vi: {
    code: {
      "000": "Đã có lỗi sảy ra",
      "001": "Tài khoản đã tồn tại",
      "002": "Đăng ký tài khoản thành công",
      "003": "Đăng nhập thành công",
      "004": "Mật khẩu sai",
      "005": "Tài khoản không tồn tại",
      "006": "Tên đăng nhập hoặc mật khẩu ít hơn 6 ký tự",
    },
    login: {
      title: "Đăng nhập tài khoản Zalo để kết nối với ứng dụng Zalo Web",
      password: "Mật khẩu",
      username: "Tên đăng nhập",
      loginwithpassword: "Đăng nhập với mật khẩu",
      forgotpassword: "Quên mật khẩu?",
      noaccount: "Bạn chưa có tài khoản ?",
      registernewaccount: "Đăng ký tài khoản mới",
    },
    register: {
      title: "Đăng ký tài khoản Zalo để kết nối với ứng dụng Zalo Web",
      password: "Mật khẩu",
      username: "Tên đăng nhập",
      showname: "Tên hiển thị",
      register: "Đăng ký",
      backlogin: "Quay về trang log in",
      male: "Nam",
      female: "Nữ",
    },
    mainlayout: {
      message: "Tin nhắn",
      phonebook: "Danh bạ",
      todo: "To-Do",
      mycloude: "Cloude của tôi",
      setting: "Cài đặt",
      screencapture: "Chụp màn hình không kèm cửa sổ",
      tool: "Công cụ",
      zavi: "Zavi",
      setting: "Cài đặt",
      search: "Tìm kiếm",
      addfriend: "Thêm bạn",
      creategroupchat: "Tạo nhóm chat",
      close: "Đóng",
    },
    nopage: {
      backhome: "Quay về trang chủ",
    },
    navlist: {
      listfriend: "Danh sách bạn bè",
      listgroup: "Danh sách nhóm",
      requestfriend: "Lời mời kết bạn",
      waitingagree: "Đã gửi lời mời",
    },
    detailcontent: {
      waitingagree: "Đã gửi lời mời",
      searchmessage: "Tìm kiếm tin nhắn",
      infoconversation: "Thông tin hội thoại",
      agree: "Đồng ý",
      addfriend: "Kết bạn",
      isfriend: "Đã là bạn",
      findinmessage: "Tìm kiếm trong tin nhắn",
      infoconversation: "Thông tin hội thoại",
      inputmesageto: "Nhập tin nhắn tới ",
      send: "GỬI",
      you: "Bạn",
      sendimage: "Gửi hình ảnh",
      image: "Ảnh",
      linh: "Link",
    },
    module: {
      cantfinduser: "Không tìm thấy người dùng",
      confirm: "Xác nhận",
      no: "Không",
      remove: "Xóa",
      outlistfriend: "khỏi danh sách bạn bè ?",
      plsenterusername: "Hãy nhập username cần kết bạn !",
      youwantlogout: "Bạn có muốn đăng xuất khỏi Zalo?",
      logout: "Đăng xuất",
      infoaccount: "Thông tin tài khoản",
      infopersonal: "Thông tin cá nhân",
      updateinfo: "Cập nhật thông tin",
      showname: "Tên hiển thị",
      pleaseuserealname: "Sử dụng tên thật để bạn bè dễ dàng nhận diện hơn",
      update: "Cập nhật",
      cancel: "Hủy",
      addfriend: "Thêm bạn",
      username: "Tên đăng nhập (username)",
    },
    popper: {
      watchinfo: "Xem thông tin",
      namechangereminder: "Đổi tên gợi nhớ",
      removefriend: "Xóa bạn",
      infoofyou: "Hồ sơ của bạn",
      infoaccount: "Thông tin tài khoản",
      setting: "Cài đặt",
      logout: "Đăng xuất",
      language: "Ngôn ngữ",
    },
    welcome: {
      title: "Chào mừng đến với ",
      description:
        "Khám phá những tiện ích hỡ trợ làm việc và trò truyện cùng người thân, bạn bè được tối ưu hóa cho máy tính của bạn.",
      slide0: {
        title: "Gọi nhóm và làm việc hiệu quả với Zalo Group Call",
        description: "Trao đổi công việc mọi lúc, mọi nơi",
      },
      slide1: {
        title: "Giải quyết công việc hiệu quả hơn, lên đến 40%",
        description: "Với Zalo Web",
      },
      slide2: {
        title: "Chat nhóm với đồng nghiệp",
        description: "Tiện lợi hơn, nhờ công cụ chat trên máy tính",
      },
      slide3: {
        title: "Gửi file nặng?",
        description: "Đã có Zalo Web xửa hết",
      },
      slide4: {
        title: "Trải nghiệm xuyên suốt",
        description:
          "Kết nối và giải quyết công việc trên mọi thiết bị với dữ liệu luôn được đồng bộ",
      },
      slide5: {
        title: "Xuất dữ liệu khi chuyển máy, đổi máy tính mới",
        description:
          "Bây giờ bạn có thể dễ dàng xuất dữ liệu và nhập dữ liệu lịch sử trò truyện của mình khi thay đổi máy tính mới",
      },
      slide6: {
        title: "Tin nhắn tự xóa",
        description:
          "Tự giờ tin nhắn có thể tự xóa sau khoảng thời gian nhất định",
      },
      slide7: {
        title: "Mã hóa đầu cuối",
        description:
          "Nội dung tin nhắn được mã hóa trong suốt quá trình xóa và nhận",
      },
      slide8: {
        title: "Nhắn tin nhiều hơn, soạn thảo ít hơn",
        description:
          "Sử dụng tin nhắn nhanh để lưa trữ các tin nhắn thường dùng và gửi nhanh trong hội thoại bất kỳ",
      },
    },
  },
};
